### ISSUE TITLE
Intégration template login & register

### ISSUE THREAD

**Issue by SteveHoareau18** [SteveHoareau18/channel-messenger#15]
- Implémenter le template suivant pour la page de login et register en adaptant pour chaque page : https://tailwindcomponents.com/component/login-template

**Comment by kotou-boina** [comment]
- Login

![Image](https://github.com/SteveHoareau18/channel-messenger/assets/114469312/40768ea9-d3cf-440c-a7c5-bd4fe2b71358)

- Register

![Image](https://github.com/SteveHoareau18/channel-messenger/assets/114469312/fedfa15d-ed31-4073-9a3a-0b3ce8d2d8bb)
