### ISSUE TITLE
Recherche de template

### ISSUE THREAD

**Issue by SteveHoareau18** [SteveHoareau18/channel-messenger#2]
Rechercher un template afin de gagner du temp de dévelopement et avoir que des intégrations à réaliser ou à construire à l'aide d'un template ou autre.
Mobile/Webapp

**Comment by Alexandre-re-RE** [comment]
Difficulty: 8

**Comment by Alexandre-re-RE** [comment]
Template application de tchat retenu: https://tailwindcomponents.com/component/quickchat-chat-layout

**Comment by Alexandre-re-RE** [comment]
Template login et register: https://tailwindcomponents.com/component/login-template
