### ISSUE TITLE
Gestion messagerie basique

### ISSUE THREAD

**Issue by SteveHoareau18** [SteveHoareau18/channel-messenger#20]
- Visualiser tout les messages de ses channel.
- Envoyer des messages.
- Supprimer ses messages.

**Comment by kotou-boina** [comment]
Terminé : [https://github.com/SteveHoareau18/channel-messenger/commit/8a7ee2f5a9e378f5541c0776995ac65e70312ca4](https://github.com/SteveHoareau18/channel-messenger/commit/8a7ee2f5a9e378f5541c0776995ac65e70312ca4)
