### ISSUE TITLE
Authentification webapp

### ISSUE THREAD

**Issue by SteveHoareau18** [SteveHoareau18/channel-messenger#7]
- Créer une entity User avec les champs (username, email, password)
- Créer une entity Channel (name, token, owner_id, belongsToMany users)

- Pouvoir créer un compte.
- Pouvoir se connecter à son compte.
- Pouvoir se déconnecter.

**Comment by Alexandre-re-RE** [comment]
Difficulty: 13

**Comment by kotou-boina** [comment]
[https://github.com/SteveHoareau18/channel-messenger/commit/1f8cb5db98b0ea4b128d38c52c80b5ed8bb8ac17](https://github.com/SteveHoareau18/channel-messenger/commit/1f8cb5db98b0ea4b128d38c52c80b5ed8bb8ac17)
